import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import prettierConfig from 'eslint-config-prettier';
import imp from 'eslint-plugin-import';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import mobx from 'eslint-plugin-mobx';
import nestjs from 'eslint-plugin-nestjs';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import security from 'eslint-plugin-security';
import globals from 'globals';

export default [
  // Global ignores
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.react-router/**',
      '**/build/**',
      '**/*.d.ts',
      // generated by shadcn/ui
      'apps/frontend/app/components/ui/*',
      'apps/frontend/app/hooks/*',
    ],
  },
  // React component configuration
  {
    files: ['**/app/routes/**/*.tsx', '**/app/root.tsx'],
    rules: {
      'import/no-default-export': 'off',
    },
  },
  // Source files configuration (common rules)
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.test.ts', '**/*.test.tsx', '**/prisma/*.ts'],
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.react-router/**',
      '**/build/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/logs/**',
      '**/.cache/**',
    ],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: [
          './apps/*/tsconfig.json',
          './apps/*/tsconfig.build.json',
          './packages/*/tsconfig.json',
        ],
        tsconfigRootDir: '.',
        ecmaFeatures: {
          jsx: true,
        },
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2022,
      },
    },
    settings: {
      react: {
        version: '19',
      },
      'import/resolver': {
        typescript: {
          project: [
            './apps/*/tsconfig.json',
            './apps/*/tsconfig.build.json',
            './packages/*/tsconfig.json',
          ],
          alwaysTryTypes: true,
        },
        node: {
          project: [
            './apps/*/tsconfig.json',
            './apps/*/tsconfig.build.json',
            './packages/*/tsconfig.json',
          ],
          moduleDirectory: ['node_modules', 'apps/frontend/node_modules'],
        },
      },
      'import/parsers': {
        '@typescript-eslint/parser': ['.ts', '.tsx'],
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      import: imp,
      security,
    },
    rules: {
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0, maxBOF: 0 }],
      'no-console': ['error', { allow: ['warn', 'error', 'info', 'debug'] }],

      /* TypeScript Rules */
      '@typescript-eslint/explicit-function-return-type': [
        'error',
        {
          allowExpressions: true,
          allowConciseArrowFunctionExpressionsStartingWithVoid: true,
          allowTypedFunctionExpressions: true,
        },
      ],
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/consistent-type-imports': 'warn',
      '@typescript-eslint/no-floating-promises': 'warn',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/strict-boolean-expressions': [
        'error',
        {
          allowString: true,
          allowNullableString: true,
          allowNumber: true,
          allowNullableNumber: true,
          allowNullableObject: true,
        },
      ],
      semi: ['error', 'always'],

      /* Import Rules */
      'import/order': ['warn', { 'newlines-between': 'always' }],
      'import/no-cycle': 'error',
      'import/no-unresolved': 'error',
      'import/no-deprecated': 'warn',

      /* Security Rules */
      // 'security/detect-non-literal-fs-filename': 'warn',
      // 'security/detect-unsafe-regex': 'error',
      // 'security/detect-buffer-noassert': 'error',
      // 'security/detect-child-process': 'error',
      // 'security/detect-disable-mustache-escape': 'error',
      // 'security/detect-eval-with-expression': 'error',
      // 'security/detect-no-csrf-before-method-override': 'error',
      // 'security/detect-possible-timing-attacks': 'error',
      // 'security/detect-pseudoRandomBytes': 'error',
    },
  },
  // Frontend specific configuration
  {
    files: ['**/apps/frontend/**/*.ts', '**/apps/frontend/**/*.tsx'],
    plugins: {
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
      mobx,
    },
    settings: {
      react: {
        version: '19',
      },
    },
    rules: {
      /* React Rules */
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react/jsx-uses-react': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/jsx-no-target-blank': 'error',
      'react/jsx-no-script-url': 'error',
      'react/no-danger': 'error',
      'react/display-name': ['error', { ignoreTranspilerName: false }],

      /** MobX Rules */
      'mobx/exhaustive-make-observable': 'warn',
      'mobx/unconditional-make-observable': 'error',
      'mobx/missing-make-observable': 'error',
      'mobx/missing-observer': 'warn',
    },
  },
  // Backend specific configuration
  {
    files: ['**/apps/backend/**/*.ts'],
    plugins: {
      nestjs,
    },
    rules: {
      /* NestJS Rules */
      'nestjs/use-validation-pipe': 'off',
    },
  },
  prettierConfig,
];
